### ISSUE TITLE
Logging: print_level does not work

### ISSUE THREAD

**Issue by MarkoBL** [mautrix/whatsapp#314]
Hi,

setting the logging print_level doesn't have any affect. The log is still filled witih all types of messages. When I set it to error, I still get all the debug and info messages:

```
logging:
  directory: ./logs
  file_name_format: '{{.Date}}-{{.Index}}.log'
  file_date_format: "2006-01-02"
  file_mode: 384
  timestamp_format: Jan _2, 2006 15:04:05
  print_level: error
```
