### ISSUE TITLE
Double puppeting is not working in 0.2.0

### ISSUE THREAD

**Issue by MarkoBL** [mautrix/whatsapp#385]
Hi,

it seems that double puppeting is currently not working for me. I set the following in the config file (it is working with the telegram and signal bridge):

```
bridge:
  double_puppet_server_map:
    bridge: http://127.0.0.1:8008
  login_shared_secret_map:
    bridge: mysecret
```

But this is ignored. When I generate a new config.yaml with `mautrix-whatsapp-amd64 -g`, these options are removed from the config at all. And manually adding them afterwards to the generated config.yaml still doesn't work.

Thanks
