### ISSUE TITLE
Unable to import history

### ISSUE THREAD

**Issue by wobblywob** [mautrix/whatsapp#475]
Hello and thanks for this cool bridge. I have an issue and most likely it's something on my end. I'd appreciate some pointers.

I'm unable to import whatsapp history at all. I've started from scratch with synapse and mautrix-whatsapp via docker containers, each with its own postgres db. The bridge seems to work, I can send/receive whatsapp messages, groups rooms are created, but no direct chats are created initially. These appear once I receive a new message from a contact.

I've went through the logs and didn't see anything suspicios. When issuing `!wa backfill` in a chat I'd get:

`[User/@user:matrix.domain.com/DEBUG] Could not find history sync conversation data for[redacted source phone no]@s.whatsapp.net-[redacted destination phone number]@s.whatsapp.net`

I think this is the relevant section in mautrix config.yaml
```
history_sync:
  create_portals: true
  backfill: true
  double_puppet_backfill: true
  request_full_sync: true
  max_initial_conversations: 1000
  immediate:
    worker_count: 1
    max_events: 100
  deferred:
            # Last Week
            - start_days_ago: 7
              max_batch_events: 40
              batch_delay: 5
            # Last Month
            - start_days_ago: 30
              max_batch_events: 100
              batch_delay: 10
            # Last 3 months
            - start_days_ago: 90
              max_batch_events: 100
              batch_delay: 10
            # The start of time
            - start_days_ago: -1
              max_batch_events: 500
              batch_delay: 10
```

I've added this line in synapse homeserver.yaml

```
experimental_features:
  msc2716_enabled: true
```
Double puppet also works according to mautrix-whatsapp docker logs:
```

[Apr 19, 2022 11:23:21] [User/@user:matrix.domain.com/DEBUG] Checking if double puppeting needs to be enabled
[Apr 19, 2022 11:23:21] [User/@user:matrix.domain.com/DEBUG] User already has double-puppeting enabled
```
