### ISSUE TITLE
Relaybot not working at all, "invites" and "management" vanishes from config.yml

### ISSUE THREAD

**Issue by jacotec** [mautrix/whatsapp#572]
I'm suffering getting the relaybot working. Unfortunately there is not a really good documentation, the only one I found was this: https://mau.dev/mautrix/docs/-/blob/9ca3e82a4fba6e6e36e40fc1aca4c987835bb430/bridges/go/whatsapp/relaybot.md

However, the "relaybot:" config section seems to be renamed to "relay:" when I look into the sample config.yml. So my config looks like this:

```
    # Settings for relay mode
    relay:
        # Whether relay mode should be allowed. If allowed, `!wa set-relay` can be used to turn any
        # authenticated user into a relaybot for that chat.
        enabled: true
        # Should only admins be allowed to set themselves as relay users?
        admin_only: true
        management: !gwILrLJxxxxxxxSnue:mydomain.de
        invites: ['@user1:mydomain.de', '@user2@mydomain.de']
        # The formats to use when sending messages to WhatsApp via the relaybot.
        message_formats:
            m.text: "<b>{{ .Sender.Displayname }}</b>: {{ .Message }}"
            m.notice: "<b>{{ .Sender.Displayname }}</b>: {{ .Message }}"
            m.emote: "* <b>{{ .Sender.Displayname }}</b> {{ .Message }}"
            m.file: "<b>{{ .Sender.Displayname }}</b> sent a file"
            m.image: "<b>{{ .Sender.Displayname }}</b> sent an image"
            m.audio: "<b>{{ .Sender.Displayname }}</b> sent an audio file"
            m.video: "<b>{{ .Sender.Displayname }}</b> sent a video"
            m.location: "<b>{{ .Sender.Displayname }}</b> sent a location"

```

After restarting the bridge, my "management" and "invites" lines are simply magically deleted out of the config. Which leads to a non-working relay.

When I create a management room in my secret relay user, inviting user1, user2 and then the bridge bot, I can login my WA account as expected.

And now?

When I then write a WA message to the connected number from a different account, only my secret relay user gets an invitation to the portal. My two users who should handle the WA account do not get any invitation at all (due to the magically purged "invites" configuration). Also it's not clear to me how the two users can create a new conversation to a Whatsapp number using the "relay WA account".
