### ISSUE TITLE
Permissions as YAML sequence

### ISSUE THREAD

**Issue by Gredin67** [mautrix/whatsapp#584]
## Problem
- [permissions are listed as objects](https://github.com/mautrix/whatsapp/blob/master/example-config.yaml#L411-L414). 
- It makes it tiring to parse

## Solution
Change to rough YAML sequences
```
permissions:
        relay:
            - *
        user:
            - "example.com"
            - "@user:example.com"
        admin:
            - "@admin:example.com"
```

## Benefits
It would be super easy to parse. 
And avoid mistakes of people changing the value manually in the `config.yaml` file
